### ISSUE TITLE
wp_mail $attachments argument is dropped

### ISSUE THREAD

**Issue by Sam-Costigan** [Rareloop/lumberjack-email#1]
Thanks for the great work on this package! I was just wondering why the decision was made to not support the `$attachments` argument to `wp_mail`? I have come across a situation where I need it, and I ended up having to rewrite every method in `src/Email.php` just to pass it along. Could it be added as an optional argument, defaulting to an empty array? The `send` method in `src/Email.php` might then look like:
```php
    private function send($to, $subject, $body, $replyTo = false, $attachments = [])
    {
        $headers = [];

        if ($replyTo) {
            $headers[] = 'Reply-To: <'.$replyTo.'>';
        }

        $fromName = Config::get('email.from.name');
        $fromEmail = Config::get('email.from.email');

        if ($fromName && $fromEmail) {
            $headers[] = 'From: '.$fromName.' <'.$fromEmail.'>';
        }

        // If we're not in production then we should add a prefix to the subject line with the env
        if (Config::get('app.environment') !== 'production') {
            $subject = '['.strtoupper(Config::get('app.environment')).'] '.$subject;
        }

        return wp_mail($to, $subject, $body, $headers, $attachments);
    }
```
I believe this would be a non-breaking change and would enable the use of attachments when necessary.

**Comment by joelambert** [comment]
Hi @Sam-Costigan, thanks for raising this. Seems like a sane suggestion to me.

Are you able to put together a PR with the changes that we can review please?

**Comment by joelambert** [comment]
All merged, thanks @Sam-Costigan 👍
